port 1194
proto udp
dev tun

# Utilisation d'une clé statique (Pas de certificats)
secret /etc/openvpn/static.key

# IP du point à point (IP Serveur | IP Client)
ifconfig 10.8.0.1 10.8.0.2

keepalive 10 120
cipher AES-256-GCM
persist-key
persist-tun
status openvpn-status.log
verb 3
