port 1194
proto udp
dev tun

# Certificats et clés (Chemins vers des fichiers qui devront être générés)
ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
dh /etc/openvpn/dh.pem

# Réseau VPN (pour les clients)
server 10.8.0.0 255.255.255.0

# Route pour accéder au lab (172.16.0.0/24)
push "route 172.16.0.0 255.255.255.0"

# DNS du lab
push "dhcp-option DNS 172.16.0.2"

keepalive 10 120
cipher AES-256-GCM
persist-key
persist-tun
status openvpn-status.log
verb 3
