services:
  dns:
    build: ./dns
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      sae_net:
        ipv4_address: 172.16.0.2

  ntp:
    build: ./ntp
    container_name: ntp
    cap_add:
      - SYS_TIME
    ports:
      - "123:123/udp"
    networks:
      sae_net:
        ipv4_address: 172.16.0.3


networks:
  sae_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
