# chrony.conf

# Serveurs de temps
server pool.ntp.org iburst

# Fichier de dérive
driftfile /var/lib/chrony/chrony.drift

# Synchronisation avec l'horloge matérielle
rtcsync

# Ajustement rapide de l'horloge au démarrage
makestep 1.0 3

# Autoriser le réseau local
allow all