options {
    directory "/var/cache/bind";
    recursion yes;
    allow-query { any; };
    listen-on { any; };
    dnssec-validation auto;

    forwarders {
        8.8.8.8;
        8.8.4.4;
        1.1.1.1;
    };
};

zone "lab.local" {
    type master;
    file "/etc/bind/lab.local.zone";
};
