options {
    directory "/var/cache/bind";
    recursion yes;
    allow-query { any; };
    listen-on { any; };
    dnssec-validation auto;
};

zone "lab.local" {
    type master;
    file "/etc/bind/lab.local.zone";
};
